apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-init-container
  labels:
    app: nginx
spec:
  initContainers:
  - name: init-setup
    image: busybox:1.28
    command: ['sh', '-c']
    args:
    - echo "Initializing...";
      sleep 10;
      echo "Setup complete" > /shared-data/init-status.txt;
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: shared-data
    emptyDir: {}
