apiVersion: batch/v1
kind: CronJob
metadata:
  name: math-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: calculator
            image: busybox
            command: ["sh", "-c", "echo 'Current time:' $(date) && echo '5 * 3 =' && expr 5 \* 3"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
