apiVersion: batch/v1
kind: Job
metadata:
  name: math-calculation
spec:
  completions: 3
  parallelism: 2
  template:
    spec:
      containers:
      - name: calculator
        image: busybox
        command: ["sh", "-c", "echo '3 + 2 =' && expr 3 + 2"]
      restartPolicy: Never
  backoffLimit: 4
