apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "webapp.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: /tmp/{{ include "webapp.fullname" . }}-data
