apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-secret
type: Opaque
data:
  username: {{ .Values.secret.username | b64enc }}
  password: {{ .Values.secret.password | b64enc }}
